services:
  backend:
    build: ./backend
    container_name: cartify_backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend/.env
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/staticfiles:/staticfiles

  frontend:
    build: ./frontend
    container_name: cartify_frontend
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    container_name: cartify_db
    env_file:
      - backend/.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: cartify_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/staticfiles:/staticfiles:ro 

volumes:
  pgdata:
  staticvolume:
  staticfiles: