FROM python:3

WORKDIR /cartify

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENV PYTHONUNBUFFERED=1

CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py migrate api && python manage.py seed && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]